import Head from "next/head";
import Image from "next/image";

import styles from "@/styles/Home.module.scss";
import NavBar from "@/components/NavBar";
import Article from "@/components/Article";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar></NavBar>
        <div>Intro Search </div>
        <div>News</div>
        <div>Cards</div>
        <Article></Article>
        <div>Themes</div>
        <div>Materials</div>
        <Article></Article>
        <div>Footer component</div>
      </main>
    </>
  );
}
